version: '3.8'
services:
  discbot:
    build: ./
    restart: always
    container_name: discbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=postgres
      - DB_DATABASE=${DB_DATABASE}
